### ISSUE TITLE
Extracting feature fails on RTX2080ti due to insufficient memory size

### ISSUE THREAD

**Issue by Wataru-Nakata** [dhimasryan/MOSA-Net-Cross-Domain#2]
The command 
```
 python3 Extracting_Hubert_Feature_VoiceMOS_Challenge.py --track phase1-main
```
fails due to insufficient memory size on RTX2080ti, but the program works when forward propagation is wrapped around `with torch.no_grad()`.

I'll send PR regarding this issue

**Comment by dhimasryan** [comment]
Hi, thanks for informing me about this issue. I have confirmed your PR.
