### ISSUE TITLE
error in pre trained model

### ISSUE THREAD

**Issue by dmumtaz** [dhimasryan/MOSA-Net-Cross-Domain#6]
I am using the **MOSA-Net_Cross_Domain_epoch_100.h5** pre-trained model to test my data but it is showing the following error:

**ValueError: Layer count mismatch when loading weights from file. Model expected 21 layers, found 17 saved layers.**

**Comment by dhimasryan** [comment]
Hi, if you want to use the following pre-trained model, please use the following [code](https://github.com/dhimasryan/MOSA-Net-Cross-Domain/blob/main/MOSA-Net_Cross_Domain_VoiceMOS_Challenge.py) to test your model.

**Comment by ruohoruotsi** [comment]
Hi @dhimasryan , I got the VoiceMOS Challenge pretrained model working, 👏  but I'd like to try to predict `Model(outputs=[PESQ_score, Frame_score, STOI_score , Frame_stoi, SDI_score, Frame_sdi]` which lives in [MOSA-Net_Cross_Domain.py](https://github.com/dhimasryan/MOSA-Net-Cross-Domain/blob/main/MOSA-Net_Cross_Domain.py) Do you have a pre-trained model for this?

**Comment by dhimasryan** [comment]
Hi @ruohoruotsi , I have uploaded the model, but please be noted that the model is trained on WSJ dataset. Here is the model [path](https://github.com/dhimasryan/MOSA-Net-Cross-Domain/tree/main/PreTrained_WSJ). Thanks
